# Generated by Django 2.2.2 on 2019-06-09 09:39

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_categoryindex_kakita_nagara_shimanto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('url', wagtail.core.fields.StreamField([('html', wagtail.core.blocks.RawHTMLBlock())])),
            ],
            options={
                'verbose_name_plural': 'advertisements',
            },
        ),
    ]
