# Generated by Django 2.2.2 on 2019-06-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0007_auto_20190611_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_page',
            field=models.ForeignKey(blank=True, help_text='Select a Form that will be embedded on this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedded_form_page', to='wagtailcore.Page'),
        ),
    ]
